//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Model.Context.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblParent
    {
        public int ParentID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public int MaritalStautsID { get; set; }
        public int GenderID { get; set; }
        public string CNICNumber { get; set; }
        public int RelationShipID { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string MailingAddress { get; set; }
        public int CountryID { get; set; }
        public int StateID { get; set; }
        public int CityID { get; set; }
        public int ZipCode { get; set; }
        public string CellNumber { get; set; }
        public string TelephoneRes { get; set; }
        public string TelephoneOffice { get; set; }
        public string JobDetail { get; set; }
        public string ProfilePicture { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string IPAddress { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual TblGenCity TblGenCity { get; set; }
        public virtual TblGenCountry TblGenCountry { get; set; }
        public virtual TblGenGender TblGenGender { get; set; }
        public virtual TblGenMaritalStaut TblGenMaritalStaut { get; set; }
        public virtual TblGenRelationShip TblGenRelationShip { get; set; }
        public virtual TblGenState TblGenState { get; set; }
    }
}
