//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Model.Context.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_GetParentByParentID
    {
        public int ParentID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string MaritalStauts { get; set; }
        public string Gender { get; set; }
        public string CNICNumber { get; set; }
        public string RelationShip { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string MailingAddress { get; set; }
        public string CountryName { get; set; }
        public string CountryCode { get; set; }
        public string StateName { get; set; }
        public string CityName { get; set; }
        public int ZipCode { get; set; }
        public string CellNumber { get; set; }
        public string TelephoneRes { get; set; }
        public string TelephoneOffice { get; set; }
        public string JobDetail { get; set; }
        public string ProfilePicture { get; set; }
        public bool IsActive { get; set; }
        public string CreatedDate { get; set; }
        public string IPAddress { get; set; }
    }
}
